include theos/makefiles/common.mk

APPLICATION_NAME = kiteplayer
kiteplayer_FILES = main.m kiteplayerApplication.mm RootViewController.mm
kiteplayer_FRAMEWORKS = UIKit AudioToolbox
include $(THEOS_MAKE_PATH)/application.mk
